DROP TABLE SCOTT.uzlet CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.konyv CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.kiado CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.kiadta CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.szerzoje CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.mufaja CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.felhasznalo CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.kedvence CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.ertekeles CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOTT.tetel CASCADE CONSTRAINTS PURGE;

COMMIT;