DROP TABLE uzlet CASCADE CONSTRAINTS PURGE;
DROP TABLE konyv CASCADE CONSTRAINTS PURGE;
DROP TABLE kiado CASCADE CONSTRAINTS PURGE;
DROP TABLE kiadta CASCADE CONSTRAINTS PURGE;
DROP TABLE szerzoje CASCADE CONSTRAINTS PURGE;
DROP TABLE mufaja CASCADE CONSTRAINTS PURGE;
DROP TABLE felhasznalo CASCADE CONSTRAINTS PURGE;
DROP TABLE kedvence CASCADE CONSTRAINTS PURGE;
DROP TABLE ertekeles CASCADE CONSTRAINTS PURGE;
DROP TABLE tetel CASCADE CONSTRAINTS PURGE;

COMMIT;